# sfnode/configs/ldl.yaml
name: LDL_Experiment

model:
  class_path: models.mlp_model.MLPModel
  init_args:
    # --- 维度 (会被 auto_run 覆盖) ---
    data_dim: 243
    output_dim: 6
    latent_dim: 256
    hidden_dim: 256 
    
    f_add_blocks: 0
    h_add_blocks: 4
    g_add_blocks: 0
    
    in_proj: linear 
    out_proj: linear
    proj_norm: null 
    
    method: ours
    force_zero_prob: 0.1
    metric_type: avg_imp
    label_scaler: null

    scheduler: cos      
    lr: 3e-4             
    wd: 0.0              
    task_criterion: mse  
    dynamics: linear     
    adjoint: false      
    label_ae_noise: 10.0

trainer:
  val_check_interval: 1960
  check_val_every_n_epoch: null
  max_steps: 100000     
  log_every_n_steps: 1
  gradient_clip_val: 0
  
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: SFNO_exp
      log_model: false
      save_dir: ./logs
      offline: true
  callbacks:
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
    
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint 
      init_args: 
        save_last: true
        monitor: 'val/avg_imp' 
        save_top_k: 1
        mode: max
        dirpath: null
        
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint 
      init_args:
        save_top_k: -1
        dirpath: null
        train_time_interval: '24:0:0'
        
    - class_path: lightning.pytorch.callbacks.RichModelSummary
      init_args:
        max_depth: 10

data:
  dataset: SBU_3DFE
  batch_size: 1024     
  test_batch_size: 768 
  task_type: ldl  

seed_everything: 0 